# Site settings
title: Ian Jones' Blog
email: jones58ian@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I would love to chat about any of my posts, reach out to me on twitter at @_jonesian or email me at jones58ian@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: _jonesian
github_username:  ijones16

gems:
  - jemoji
  - jekyll-mentions
  - jekyll-sitemap

jekyll-mentions:
  base_url: https://twitter.com

# Build settings
markdown: kramdown
