# Site settings
title: Ian Jones' Blog
email: jones58ian@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This site documents my learnings over the years. I focus on Javascript
  and all the frameworks that have come out of it.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: _jonesian
github_username:  ijones16

gems:
  - jemoji
  - jekyll-mentions
  - jekyll-sitemap

jekyll-mentions:
  base_url: https://twitter.com

# Build settings
markdown: kramdown
